# Generated by Django 3.2.9 on 2021-12-21 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_alter_event_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 16, 23, 39, 544874, tzinfo=utc)),
        ),
    ]
